templates = { };
templates.designer = [

  "<div id='designerIcon'><img src='art\/Designer\/designer_icon.png'\/><\/div>",

  "<ul id='menu'>",
  "  <!-- li class='ui-state-disabled'>Aberdeen<\/li -->",
  "  <li>Levels",
  "    <ul>",
  "      <li id='loadLevel'>Load Level<\/li>",
  "      <li id='saveLevel'>Save Level<\/li>",
  "      <li id='newLevel'>New Level<\/li>",
  "    <\/ul>",
  "  <\/li>",
  "  <li id='player'>Player<\/li>",
  "  <li id='tiles'>Tiles<\/li>",
  "  <li id='objects'>Objects<\/li>",
  "  <li id='platforms'>Platforms<\/li>",
  "  <li id='baddiesLevel'>Baddies<\/li>",
  "<\/ul>",

  "<div id='playerDialog' title='Player'>",
  "  <canvas id='playerCanvas'><\/canvas>",
  "<\/div>",

  "<div id='newLevelDialog' title='New level'>",
  " <div>",
  "   <table>",
  "     <tr>",
  "       <td><input id='txtNewLevel' type='textbox' value='' width=50\/><\/td>",
  "       <td><input id='btnNewLevel' type='button' value='Create'\/><\/td>",
  "     <\/tr>",
  "   <\/table>",
  " <\/div>",
  "<\/div>",

  "<div id='tilesDialog' title='Tiles'>",
  "  <div style='overflow-y:auto; height:200px;'>",
  "    <div id='tilesScrollArea'>",
  "    <\/div>",
  "  <\/div>",
  "<\/div>",

  "<div id='objectsDialog' title='Objects'>",
  "  <div style='overflow-y:auto; height:200px;'>",
  "    <div id='objectsScrollArea'>",
  "    <\/div>",
  "  <\/div>",
  "<\/div>",

  "<div id='platformsDialog' title='Platforms'>",
    " <div>",
    "  <input id='btnAddPlatform' type='button' value='add'\/>",
    "  <input id='btnEditPlatform' type='button' value='Edit'\/>",
    "  <input id='btnDeletePlatform' type='button' value='Delete'\/>",
    " <\/div>",
    " <\/p>",
    "  <div style='overflow-y:auto; height:200px;'>",
    "    <div id='platformLevelArrayScrollArea'>",
    "    <\/div>",
    "  <\/div>",
    "<\/div>",

  "<div id='platformEditorDialog' title='Platform editor'>",
  "  <div id='platformEditorTabs'>",
  "    <ul>",
  "      <li><a href='#platformEditorTabs-1'>Settings<\/a><\/li>",
  "      <li><a href='#platformEditorTabs-2'>Movement<\/a><\/li>",
  "    <\/ul>",
  "    <div id='platformEditorTabs-1'>",
  "      <table>",
  "          <tr>",
  "              <td class='label'>Sprite:<\/td>",
  "              <td style='font-weight: bold' data-bind='text: spriteSheet' \/><\/td>",
  "              <td><input type='button' value='Select' id='platformSelectSpriteSheetButton'><\/input><\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Frame interval:<\/td>",
  "              <td>",
  "                  <input data-bind='value: frameInterval' \/>",
  "              <\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Looping:<\/td>",
  "              <td>",
  "                  <input type='checkbox' data-bind='checked: loop' \/>",
  "              <\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Speed:<\/td>",
  "              <td>",
  "                  <input data-bind='value: speed' \/>",
  "              <\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Image scaling %:<\/td>",
  "              <td>",
  "                  <input data-bind='value: scaling' \/>",
  "              <\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Platform edge offset:<\/td>",
  "              <td>",
  "                  <input data-bind='value: xPadding' \/>",
  "              <\/td>",
  "          <\/tr>",

  "      <\/table>",
  "    <\/div>",
  "    <div id='platformEditorTabs-2'>",
// templates.platformMove goes here
  "    <\/div>",
  "  <\/div>",
  "<\/div>",

  "<div id='loadLevelDialog' title='Load Level'>",
  " <div>",
  "   <table>",
  "     <tr>",
  "       <td id='optionLevelDiv'><\/td>",
  "       <td><input id='btnLevelSelect' type='button' value='Open'\/><\/td>",
  "     <\/tr>",
  "   <\/table>",
  " <\/div>",
  "<\/div>",

  "<div id='baddiesLevelDialog' title='Baddies'>",
  " <div>",
  "  <input id='btnAddBaddie' type='button' value='add'\/>",
  "  <input id='btnEditBaddie' type='button' value='Edit'\/>",
  "  <input id='btnDeleteBaddie' type='button' value='Delete'\/>",
  " <\/div>",
  " <\/p>",
  " <div style='overflow-y:auto; height:200px;'>",
  "  <div id='baddiesLevelArrayScrollArea'><\/div>",
  " <\/div>",
  "<\/div>",

  // save as div placeholder
  "<div id='saveAs'><\/div>",

  "<div id='platformsAvailableDialog' title='Select a sprite'>",
  "  <div style='overflow-y:auto; height:200px;'>",
  "    <div id='platformsAvailableScrollArea'>",
  "    <\/div>",
  "  <\/div>",
  "<\/div>",

  "<div id='imagesAvailableDialog' title='Select a sprite'>",
  "  <div style='overflow-y:auto; height:200px;'>",
  "    <div id='imageScrollArea'>",
  "    <\/div>",
  "  <\/div>",
  "<\/div>",

  "<div id='baddiesAvailableDialog' title='Select a sprite'>",
  "  <div style='overflow-y:auto; height:200px;'>",
  "    <div id='baddiesAvailableScrollArea'>",
  "    <\/div>",
  "  <\/div>",
  "<\/div>",

  "<div id='spawnAvailableDialog' title='Spawn'>",
  "  <div style='overflow-y:auto; height:200px;'>",
  "    <div id='spawnAvailableScrollArea'>",
  "    <\/div>",
  "  <\/div>",
  "<\/div>",

  "<div id='baddieEditorDialog' title='Edit baddie instance'>",

  "  <div id='baddieEditorTabs'>",
  "    <ul>",
  "      <li><a href='#baddieEditorTabs-1'>Settings<\/a><\/li>",
  "      <li><a href='#baddieEditorTabs-2'>Movement<\/a><\/li>",
  "      <li><a href='#baddieEditorTabs-3'>Spawn<\/a><\/li>",
  "    <\/ul>",
  "    <div id='baddieEditorTabs-1'>",
  "      <table>",
  "          <tr>",
  "              <td class='label'>Type:<\/td>",
  "              <td style='font-weight: bold' data-bind='text: name' \/><\/td>",
  "              <td><input type='button' value='Select' id='baddieSelectSpriteButton'><\/input><\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Move type:<\/td>",
  "              <td>",
  "                  <select data-bind='options: moveTypeValues, value: moveType'><\/select>",
  "              <\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Looping:<\/td>",
  "              <td>",
  "                  <input type='checkbox' data-bind='checked: loop' \/>",
  "              <\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Points:<\/td>",
  "              <td>",
  "                  <input data-bind='value: points' \/>",
  "              <\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Facing:<\/td>",
  "              <td>",
  "                  <select data-bind='options: facingValues, value: facing'><\/select>",
  "              <\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Speed:<\/td>",
  "              <td>",
  "                  <input data-bind='value: speed' \/>",
  "              <\/td>",
  "          <\/tr>",
  "          <tr>",
  "              <td class='label'>Health decrement:<\/td>",
  "              <td>",
  "                  <input data-bind='value: healthDecrement' \/>",
  "              <\/td>",
  "          <\/tr>",
  "      <\/table>",
  "    <\/div>",
  "    <div id='baddieEditorTabs-2'>",
// templates.baddieMove goes here
  "    <\/div>",
  "    <div id='baddieEditorTabs-3'>",
// templates.baddieSpawn goes here
  "    <\/div>",
  "  <\/div>",
  "<\/div>"
].join("\n");

templates.baddieMove = [
  "   <div style='overflow-y:auto; height:200px;'>",
  "      <table data-bind='visible: moveArray().length > 0'>",
  "          <thead>",
  "              <tr>",
  "                  <th>X<\/th>",
  "                  <th>Y<\/th>",
  "                  <th \/>",
  "              <\/tr>",
  "          <\/thead>",
  "          <tbody data-bind='foreach: moveArray'>",
  "              <tr>",
  "                  <td>",
  "                      <input class='required number' data-bind='value: x, uniqueName: false' \/>",
  "                  <\/td>",
  "                  <td>\/",
  "                      <input class='required number' data-bind='value: y, uniqueName: true' \/>",
  "                  <\/td>",
  "                  <td><a href='#' data-bind='click: $root.removeMove'>Delete<\/a>",

  "                  <\/td>",
  "              <\/tr>",
  "          <\/tbody>",
  "      <\/table>",
  "   <\/div>",
  "   <button data-bind='click: addMove'>Add move<\/button>",
  "   <button data-bind='click: save'>Apply changes<\/button>"
].join("\n");

templates.baddieSpawn = [
  "        <div data-bind='ifnot: spawn.name'>",
  "           <input type='button' value='Add new spawn' id='spawnButton'><\/input>",
  "        </div>",
  "        <div data-bind='if: spawn.name'>",
  "        <table>",
  "            <tr>",
  "                <td class='label'><canvas id='spawnEditCanvas'><\/canvas><\/td>",
  "                <td\/><input type='button' value='Select sprite' id='spawnSelectSpriteButton'><\/input><\/td>",
  "            <\/tr>",
  "            <tr>",
  "                <td class='label'>Name:<\/td>",
  "                <td style='font-weight: bold' data-bind='text: spawn.name' \/><\/td>",
  "            <\/tr>",
  "            <tr>",
  "                <td class='label'>Relative X:<\/td>",
  "                <td>",
  "                    <input data-bind='value: spawn.relativeX' \/>",
  "                <\/td>",
  "            <\/tr>",
  "            <tr>",
  "                <td class='label'>Relative Y:<\/td>",
  "                <td>",
  "                    <input data-bind='value: spawn.relativeY' \/>",
  "                <\/td>",
  "            <\/tr>",
  "            <tr>",
  "                <td class='label'>Frame delay:<\/td>",
  "                <td>",
  "                    <input data-bind='value: spawn.frameDelay' \/>",
  "                <\/td>",
  "            <\/tr>",
  "            <tr>",
  "                <td class='label'>Max allowed in play:<\/td>",
  "                <td>",
  "                    <input data-bind='value: spawn.maxInPlay' \/>",
  "                <\/td>",
  "            <\/tr>",
  "            <tr>",
  "                <td class='label'>Health decrement:<\/td>",
  "                <td>",
  "                    <input data-bind='value: spawn.healthDecrement' \/>",
  "                <\/td>",
  "            <\/tr>",
  "            <tr>",
  "                <td class='label'>Spawn condition:<\/td>",
  "                <td>",
  "                    <select data-bind='options: spawn.conditionValues, value: spawn.condition'><\/select>",
  "                <\/td>",
  "            <\/tr>",
  "        <\/table>",
  "       <\/div>",
].join("\n");
